#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import sys, os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, BASE_DIR)

import cli

if __name__ == "__main__":
    sys.exit(cli.main())
